# Generated by Django 5.0.14 on 2025-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalColorEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField(blank=True, null=True)),
                ('fechaModificacion', models.DateField(blank=True, null=True)),
                ('horaCreacion', models.TimeField(blank=True, null=True)),
                ('horaModificacion', models.TimeField(blank=True, null=True)),
                ('borrado', models.BooleanField(default=False)),
                ('usuarioCreacion_id', models.IntegerField(blank=True, null=True)),
                ('usuarioModificacion_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Principal_colorempaque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalEmpaques',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField(blank=True, null=True)),
                ('fechaModificacion', models.DateField(blank=True, null=True)),
                ('horaCreacion', models.TimeField(blank=True, null=True)),
                ('horaModificacion', models.TimeField(blank=True, null=True)),
                ('borrado', models.BooleanField(default=False)),
                ('idMaterial_id', models.IntegerField(blank=True, null=True)),
                ('idTipo_id', models.IntegerField(blank=True, null=True)),
                ('idUnidadCobro_id', models.IntegerField(blank=True, null=True)),
                ('idUso_id', models.IntegerField(blank=True, null=True)),
                ('usuarioCreacion_id', models.IntegerField(blank=True, null=True)),
                ('usuarioModificacion_id', models.IntegerField(blank=True, null=True)),
                ('esCencosud', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Principal_empaques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalMolde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField(blank=True, null=True)),
                ('fechaModificacion', models.DateField(blank=True, null=True)),
                ('horaCreacion', models.TimeField(blank=True, null=True)),
                ('horaModificacion', models.TimeField(blank=True, null=True)),
                ('borrado', models.BooleanField(default=False)),
                ('usuarioCreacion_id', models.IntegerField(blank=True, null=True)),
                ('usuarioModificacion_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Principal_molde',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrincipalMoldeEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateField(blank=True, null=True)),
                ('fechaModificacion', models.DateField(blank=True, null=True)),
                ('horaCreacion', models.TimeField(blank=True, null=True)),
                ('horaModificacion', models.TimeField(blank=True, null=True)),
                ('borrado', models.BooleanField(default=False)),
                ('usuarioCreacion_id', models.IntegerField(blank=True, null=True)),
                ('usuarioModificacion_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Principal_moldeempaque',
                'managed': False,
            },
        ),
    ]
